-- SQL query to add placeholder projects to Supabase for layout testing
-- Run this in your Supabase SQL Editor

INSERT INTO projects (title, description, link, tags, created_at) VALUES
('Campus Gardening App', 'A mobile app connecting students interested in sustainable gardening and urban farming. Features include plant identification, watering schedules, and community forums.', 'https://github.com/example/campus-gardening', ARRAY['CS', 'Biology', 'Sustainability', 'Mobile'], '2024-01-15T10:30:00Z'),
('Study Buddy Matcher', 'AI-powered platform to match students with compatible study partners based on learning styles and academic goals.', 'https://github.com/example/study-buddy', ARRAY['AI', 'Psychology', 'Education', 'Machine Learning'], '2024-01-14T14:20:00Z'),
('Local Food Network', 'Connecting students with local farmers and food producers for sustainable eating and community building.', 'https://github.com/example/local-food', ARRAY['Business', 'Agriculture', 'Community', 'Sustainability'], '2024-01-13T09:15:00Z'),
('Mental Health Tracker', 'Anonymous platform for students to track and improve their mental wellness with privacy-focused features.', 'https://github.com/example/mental-health', ARRAY['Health', 'Psychology', 'Technology', 'Privacy'], '2024-01-12T16:45:00Z'),
('Campus Event Planner', 'Collaborative tool for organizing and promoting student events across campus with RSVP management.', 'https://github.com/example/event-planner', ARRAY['Event Planning', 'Marketing', 'Community', 'Management'], '2024-01-11T11:30:00Z'),
('Eco-Friendly Transport', 'Ride-sharing app focused on reducing carbon footprint through carpooling and sustainable transportation.', 'https://github.com/example/eco-transport', ARRAY['Environment', 'Transportation', 'Mobile', 'Sustainability'], '2024-01-10T13:20:00Z'),
('Virtual Study Rooms', 'Online collaborative study spaces with video, screen sharing, and productivity tools for remote learning.', 'https://github.com/example/virtual-study', ARRAY['Education', 'Web Dev', 'Video', 'Collaboration'], '2024-01-09T15:10:00Z'),
('Skill Exchange Platform', 'Students teach each other skills in exchange for learning new ones with peer-to-peer learning features.', 'https://github.com/example/skill-exchange', ARRAY['Education', 'Community', 'Peer Learning', 'Skills'], '2024-01-08T12:00:00Z'),
('Campus Safety Network', 'Real-time safety alerts and emergency response system for campus with GPS tracking and community reporting.', 'https://github.com/example/campus-safety', ARRAY['Safety', 'GPS', 'Emergency', 'Community'], '2024-01-07T08:30:00Z'),
('Academic Resource Hub', 'Centralized platform for sharing study materials, notes, and academic resources with version control.', 'https://github.com/example/academic-hub', ARRAY['Education', 'Version Control', 'Resources', 'Collaboration'], '2024-01-06T14:45:00Z'),
('Student Housing Marketplace', 'Platform for finding roommates, sublets, and housing options near campus with virtual tours.', 'https://github.com/example/housing-marketplace', ARRAY['Housing', 'Marketplace', 'VR', 'Community'], '2024-01-05T10:15:00Z'),
('Campus Fitness Tracker', 'Social fitness platform connecting students for workouts and health challenges with gamification.', 'https://github.com/example/fitness-tracker', ARRAY['Fitness', 'Health', 'Gamification', 'Social'], '2024-01-04T16:20:00Z');
